### PR TITLE
support repeat one line in killring to rect

### PR DESCRIPTION
**Pull request by shengofsun**
by which the ctrl-x-r-t can be somewhat emulated

### CODE REVIEW

**Comment by whitphx** [comment]
Hi, thank you for your contribution!

Please only fix the error occurred on the CI. It's simply a code format problem and should be fixed by following https://github.com/whitphx/vscode-emacs-mcx/blob/main/DEVELOPMENT.md#linter-and-code-formatter 👍

**Comment by shengofsun** [comment]
> Hi, thank you for your contribution!
> 
> Please only fix the error occurred on the CI. It's simply a code format problem and should be fixed by following https://github.com/whitphx/vscode-emacs-mcx/blob/main/DEVELOPMENT.md#linter-and-code-formatter 👍

code format has fixed. sorry that I didn't notice this before.

**Comment by whitphx** [comment]
Thank you!

Regarding the test failure, did it occur on your local environment?
That test case uses VSCode's auto-indent feature and might be affected with its config, like global indent setting.

**Review by whitphx — APPROVED** [review]
LGTM! Thank you 😸

**Comment by whitphx** [comment]
I merge this PR, but let's continue the discussion about the test failure :)

**Pull request merged**
